### ISSUE TITLE
FormData crashes the plugin: "requestData.__getNative not a function"

### ISSUE THREAD

**Issue by WilcoVertegaal** [benallfree/cordova-plugin-xhr-local-file#3]
Trying to upload local image data to a remote server that requires the images sent as FormData. It crashes the plugin in line 769:

```
      if (FormData.prototype.isPrototypeOf(requestData))
          requestData = requestData.__getNative();

```
telling me that requestData.__getNative is not a function. If I delete lines 768/769, all is well and everything seems to function as expected.

My suggestion would be to add a check in line 768:

```
      if (requestData && FormData.prototype.isPrototypeOf(requestData) && requestData.__getNative )
          requestData = requestData.__getNative();

```

Thanks for all the hard work.

**Comment by benallfree** [comment]
Send a PR :)

**Comment by WilcoVertegaal** [comment]
> Send a PR :)

Done :-)
